#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import json
import sys
import os
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

try:
    app_config = agent.read_envfile("mariadb.env")
except FileNotFoundError:
    #not configured?
    sys.stdout.write('module creation failed: mariadb.env not configured')
    exit(2)

try:
    app_config = agent.read_envfile("photoprism.env")
    #change corresponding values in the app_config and write to file if anything changed
    #input is a lower key, output in env file is upper version
    changed = False
    for key, value in app_config.items():
        if key.lower() in data:
            app_config[key] = data.get(key.lower())
            changed = True
            sys.stdout.write("changed %s to %s" %(key, app_config[key]))
    #if the traefik url changes
    if "host" in data: 
        app_config["PHOTOPRISM_SITE_URL"]="https://" + data.get("host")
        changed = True    
    if changed: agent.write_envfile("photoprism.env", app_config)
except FileNotFoundError:
    #should already be there
    sys.stdout.write('module creation failed: photoprism.env not configured')
    exit(2)