#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import json
import sys
import os
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

try:
    app_config = agent.read_envfile("mysql.env")
except FileNotFoundError:
    #not configured?
    print('module creation failed: mysql.env not configured')
    exit(2)

try:
    app_config = agent.read_envfile("photoprism.env")
except FileNotFoundError:
    #should already be there
    print('module creation failed: photoprism.env not configured')
    exit(2)
    
#change corresponding values in the app config and write to file if changed
changed = False
for key, value in app_config:
    if data.get(key.lower()) is not None: 
        app_config[key] = value
        changed = True
        print("changed %s to %s" %(key, value))
if changed: agent.write_envfile("photoprism.env", app_config)

