#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

#systemctl --user try-reload-or-restart photoprism.service
systemctl --user stop photoprism.service
sleep 15
systemctl --user start photoprism.service
